schemaVersion: 2.2.0
metadata:
  name: java-quarkus
components:
  - name: quarkus-dev
    container:
      sourceMapping: /projects
      memoryLimit: 8Gi
      memoryRequest: 512Mi
      volumeMounts:
        - name: m2
          path: /home/user/.m2
      image: registry.redhat.io/devspaces/udi-rhel8
      endpoints:
        - exposure: public
          name: quarkus-dev
          targetPort: 8080
          protocol: https
        - exposure: public
          name: swagger-ui
          targetPort: 8080
          protocol: https
          path: /q/swagger-ui
      env:
        - name: CHE_PLUGIN_REGISTRY_URL
          value: https://open-vsx.org
  - name: m2
    volume:
      size: 2Gi
commands:
  - exec:
      commandLine: mvn quarkus:dev
      component: quarkus-dev
      workingDir: '/projects/quarkus-quickstarts/getting-started'
      label: Start Quarkus in Dev Mode (getting-started)
    id: quarkus-dev-mode
